# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 844499c4263a2ede738f908f5dee46be47e588beae095e120682b4dca20362df3d96a808a94cd4e84627b130912003a08656676de2074eeba2823a62839dcd9d

test:
  secret_key_base: bb5cfe204c22fd2323a5bd30bd3d433cea385661406f110d1dfc94cf2882274f8f2c7ccdb19dfa612619a876bd2fe68a3d3bf9d4a81ccdf2ba1225c5b4b0a3bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
